In [ ]:
import pandas as pd

In [ ]:
df_csv = pd.read_csv("/test_Y3wMUE5_7gLdaTN.csv")

In [ ]:
df_csv.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [ ]:
df_excel = pd.read_excel(
    "/Historicalinvesttemp.xlsx",
    sheet_name="Sheet1"
)

In [ ]:
df_excel.head()

  Unnamed: 0                     Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                            NaN        NaN        NaN
1        NaN                            NaN        NaN        NaN
2        NaN                            NaN        NaN        NaN
3        NaN  Annual Returns on Investments        NaN        NaN
4       Year                         Stocks    T.Bills    T.Bonds

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

In [ ]:
import pandas as pd
import requests
from io import StringIO

headers = {"User-Agent": "Mozilla/5.0"}

html = requests.get(url, headers=headers).text

tables = pd.read_html(StringIO(html))

df_web = tables[0]

print(df_web.head())

                                                   0
0  Largest economies in the world by nominal GDP ...

In [ ]:
df_web = tables[2]

In [ ]:
df = pd.read_excel("/Historicalinvesttemp.xlsx")

In [ ]:
df.to_excel("/content/output.xlsx", index=False)

In [ ]:
df.head()

  Unnamed: 0                     Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                            NaN        NaN        NaN
1        NaN                            NaN        NaN        NaN
2        NaN                            NaN        NaN        NaN
3        NaN  Annual Returns on Investments        NaN        NaN
4       Year                         Stocks    T.Bills    T.Bonds